Инфраструктура для работы с базой данных
CIRCULARKA/info-bot pull request #1
Opened 2024-12-24 09:45 UTC by 4view

1. Инфраструктура для работы с данными
2. Инициализировал БД (создал миграции к бд)
3. Создал доменные объекты (Aticle и ArticleAttribute)
4. Создал конвертацию из доменного объекта в сущность бд и обратно
5. Написал тест для сервиса сохранения статей

2024-12-27 15:26 UTC, CIRCULARKA requested changes

2024-12-27 15:26 UTC, CIRCULARKA commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +    private readonly ApplicationDbContext _context;
2. Нихуя себе, взял мою БД задеанонил, такое коммитить нельзя. Надо будет in memory БД использовать, чтобы БД не дёргать и не палить креденшиалсы

2024-12-27 15:26 UTC, CIRCULARKA commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +        };
Можно не писать приставку `test`, из контекста итак понятно, что мы тестируем. Лучше напиши префикс `expected`, т.к. именно с этими объектами будешь сравнивать энтити. Т.е. ты ожидаешь, что энтити будет равна по свойствам этим объектам

2024-12-27 15:26 UTC, CIRCULARKA commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +            AddedAt = new DateTimeOffset(new DateTime(2024,12,25), new TimeSpan())
Пробелы после запятых

2024-12-27 15:26 UTC, CIRCULARKA commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +        var savedEntity = _context.Set<ArticleEntity>().Where(a => a.Id == a.Id).FirstOrDefault();
Условие, которое ты написал в `Where`, можно прописать в `FirstOrDefault`, т.е. `Where` тут вызывать не надо, т.к. тебе только один объект нужен

2024-12-27 15:26 UTC, CIRCULARKA commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +        _context.Database.EnsureDeleted();
Если тест провалится, то БД, которую ты для теста заспавнил, то она не удалится. Помести весь тест в try, а в finally сделай EnsureDeleted

2025-01-02 09:11 UTC, 4view commented on src/InfoBot.Core/Models/Article.cs
> +    /// <param name="entity"></param>
@CIRCULARKA fixed: [2190e04](https://github.com/CIRCULARKA/info-bot/commit/2190e04c96646ea3fdeff092f42a8dbe2514775e)

2025-01-02 09:11 UTC, 4view commented on src/InfoBot.Core/Models/Article.cs
> +    /// <exception cref="InvalidOperationException"></exception>
@CIRCULARKA fixed: [2190e04](https://github.com/CIRCULARKA/info-bot/commit/2190e04c96646ea3fdeff092f42a8dbe2514775e)

2025-01-02 09:11 UTC, 4view commented on src/InfoBot.Core/Models/Article.cs
> +            _entity.Attributes.Clear();
@CIRCULARKA fixed: [2190e04](https://github.com/CIRCULARKA/info-bot/commit/2190e04c96646ea3fdeff092f42a8dbe2514775e)

2025-01-02 09:13 UTC, 4view commented on src/InfoBot.Core/Storage/StorageResult.cs
> +    /// <param name="result">Результат операции</param>
Че удалить то, не понял

2025-01-02 09:51 UTC, 4view commented on src/InfoBot.Core/Storage/StorageResult.cs
> +    /// Создает результат, согнализирующий об успешности операции
@CIRCULARKA fixed: https://github.com/CIRCULARKA/info-bot/pull/1/commits/9b930c02f85be66fc87fa27d97173c70aeb06b08

2025-01-02 09:51 UTC, 4view commented on src/InfoBot.Core/Storage/StorageResult.cs
> +    /// <param name="result">Результат операции</param>
@CIRCULARKA fixed: https://github.com/CIRCULARKA/info-bot/commit/9b930c02f85be66fc87fa27d97173c70aeb06b08

2025-01-02 09:52 UTC, 4view commented on src/InfoBot.Core/Storage/StorageResult.cs
> +    /// Создает объект, сигнализирующий об ошибки операции
@CIRCULARKA fixed: https://github.com/CIRCULARKA/info-bot/commit/9b930c02f85be66fc87fa27d97173c70aeb06b08

2025-01-02 09:56 UTC, 4view commented on src/InfoBot.Infrastructure/Storage/ArticleStorageService.cs
> +    public ArticleStorageService(ApplicationDbContext context)
@CIRCULARKA fixed: [3d69e13](https://github.com/CIRCULARKA/info-bot/pull/1/commits/3d69e1387130d1386a081fb4b1cd1beb256d3fce)

2025-01-02 09:56 UTC, 4view commented on src/InfoBot.Infrastructure/Storage/ArticleStorageService.cs
> +        if (article == null) throw new ArgumentNullException(nameof(article));
@CIRCULARKA fixed: [3d69e13](https://github.com/CIRCULARKA/info-bot/pull/1/commits/3d69e1387130d1386a081fb4b1cd1beb256d3fce)

2025-01-02 09:56 UTC, 4view commented on src/InfoBot.Infrastructure/Storage/ArticleStorageService.cs
> +        if (article.Attributes == null || article.Attributes.Any(a => a == null))
@CIRCULARKA fixed: [3d69e13](https://github.com/CIRCULARKA/info-bot/pull/1/commits/3d69e1387130d1386a081fb4b1cd1beb256d3fce)

2025-01-02 09:56 UTC, 4view commented on src/InfoBot.Infrastructure/Storage/ArticleStorageService.cs
> +        return StorageResult.CreateSuccess("Operation executed");
@CIRCULARKA fixed: [3d69e13](https://github.com/CIRCULARKA/info-bot/pull/1/commits/3d69e1387130d1386a081fb4b1cd1beb256d3fce)

2025-01-02 16:49 UTC, 4view commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +        var savedEntity = _context.Set<ArticleEntity>().Where(a => a.Id == a.Id).FirstOrDefault();
@CIRCULARKA fixed: [42480d9](https://github.com/CIRCULARKA/info-bot/pull/1/commits/42480d9060534177992d59f4b6f3a119d864768e)

2025-01-02 16:49 UTC, 4view commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +            AddedAt = new DateTimeOffset(new DateTime(2024,12,25), new TimeSpan())
@CIRCULARKA fixed: [42480d9](https://github.com/CIRCULARKA/info-bot/pull/1/commits/42480d9060534177992d59f4b6f3a119d864768e)

2025-01-02 16:50 UTC, 4view commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +            AddedAt = new DateTimeOffset(new DateTime(2024,12,25), new TimeSpan())
@CIRCULARKA fixed: [cc74d4e](https://github.com/CIRCULARKA/info-bot/pull/1/commits/cc74d4e96d141a6a98c467267cd9caa0cac6fbbb)

2025-01-02 16:50 UTC, 4view commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +        };
@CIRCULARKA fixed: [42480d9](https://github.com/CIRCULARKA/info-bot/pull/1/commits/42480d9060534177992d59f4b6f3a119d864768e)

2025-01-02 16:50 UTC, 4view commented on src/InfoBot.Tests/Integration/Infrastructure/Storage/ArticleStorageServiceTests.cs
> +    private readonly ApplicationDbContext _context;
@CIRCULARKA fixed: [42480d9](https://github.com/CIRCULARKA/info-bot/pull/1/commits/42480d9060534177992d59f4b6f3a119d864768e)

2025-01-06 14:10 UTC, CIRCULARKA commented on src/InfoBot.Core/Models/Article.cs
> +    /// <exception cref="InvalidOperationException"></exception>
@4view 34 строка либо добавь описание, либо дельни тег

2025-01-06 15:17 UTC, CIRCULARKA approved these changes

2025-01-06 15:27 UTC, merged